import 'server-only';

import '../styles/globals.css';
import '../styles/mdx.css';
// import '../styles/gruvbox-dark.css';
// import '../styles/duotone-forest.css';
// import '../styles/forest-night-italic-serenade.css';
// import '../styles/greenery-dark-theme.css';
// import '../styles/v-theme.css';
import '../styles/forest-focus-theme.css';
// import '../styles/xonokai.css';
// import type { Metadata } from 'next';
import RootLayout from '@/components/root-layout';
import { Dosis, Inter, Open_Sans } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});
const dosis = Dosis({
  subsets: ['latin'],
  variable: '--font-dosis',
});
const open_sans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${open_sans.variable} ${dosis.variable} ${inter.variable} h-full scroll-smooth bg-[#ECEDFA] font-dosis text-base antialiased`}
    >
      <body className=" flex min-h-full flex-col">
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}

// #1F2937
