import './globals.css';
// import type { Metadata } from 'next';
import RootLayout from '@/components/root-layout';
import { Dosis, Inter, Open_Sans } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});
const dosis = Dosis({
  subsets: ['latin'],
  variable: '--font-dosis',
});
const open_sans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${open_sans.variable} ${dosis.variable} ${inter.variable} font-dosis h-full bg-[#ECEDFA] text-base antialiased`}
    >
      {/* <body className={inter.className}> */}
      <body
        // debug-screens
        className="flex min-h-full flex-col"
      >
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
